# -*- coding: utf-8 -*-
"""Challenge-28 : DigitAddition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bYPivnTCAz3B4A2oXrq2di8BBkuC_9N

# Compare two numbers (100 Marks)
For this challenge, you will take two integers input from stdin, sum the digits of a number and same is to be done with another number. Then compare the sum of the digits of two numbers and if one sum found to be greater then print that number to the stdout. If found both sum to be equal then print 'Equal' to the stdout.

Input Format
Two integer values to be taken as input from stdin. 

Constraints
1 < (a,b) < 10^9

Output Format
Print the single number after comparison. If found equal, then print 'Equal' to the stdout. 

Sample TestCase 1
Input
345678   444444
Output
345678
"""

def main():

 # Write code here 
 a,b = map(int,input().split())
 c,d = a,b
 a_sum,b_sum = 0,0
 while True:
    if a==0 and b==0:
        break
    if a > 0:
        a_sum = a_sum + (a%10)
        a = int(a/10)
    if b > 0:
        b_sum = b_sum + (b%10)
        b = int(b/10)
 if a_sum>b_sum:
    print(c,end='')
 elif b_sum>a_sum:
    print(d,end='')
 else:
    print("Equal",end='')
main()